# Generated by Django 5.1.5 on 2025-01-31 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="story",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Story",
                "verbose_name_plural": "Stories",
            },
        ),
    ]
